pythonProject/djangosite/djangosite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject/djangosite/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('course/<int:id>/', views.coursepg, name='course_detail'),
    path('', views.mainpage, name = 'home'),
    path('profile/', views.profile_pg, name = 'profile'),
    path('search/', views.search_view, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('catalog/', views.course_catalog, name='catalog'),
    path('filter_courses/', views.filter_courses, name='filter_courses'),
    path('teaching/', views.teaching_page, name='teaching'),
    path('course/<int:id>/edit/', views.edit_course, name='edit_course'),
    path('course/<int:id>/progress/', views.course_progress, name='course_progress'),
    path('course/module/<int:id>/', views.module_detail, name='module_detail'),
    path('payment/<int:course_id>/', views.payment_view, name='payment')
]

pythonProject/djangosite/main/models.py
from django.db import models
from enum import Enum
from django.contrib.auth.models import User




class Tags(Enum):
    C_SHARP = 'C#'
    C_PLUS = 'C++'
    PYTHON = 'Python'
    JAVA = 'Java'
    HTML_CSS = 'HTML/CSS'
    DJANGO = 'Django'
    REACT = 'React'
    NODE = 'Node.js'
    FLASK = 'Flask'
    PANDAS = 'Pandas'
    FRONT = 'Frontend-разработка'
    BACK = 'Backend-разработка'
    JS = 'JavaScript'
    SQL = 'SQL'
    MACHINE = 'Машинное обучение'
    DATA = 'Анализ данных'
    MATH = 'Теория вероятностей и мат. статистика'
    ANDROID = 'Android'
    IOS = 'IOS'

class DifficultyLevel(Enum):
    FOR_BEGIN = 'Для начинающих'
    FOR_INTER = 'Для уверенных'
    FOR_PRO = 'Для профессионалов'
    FOR_ALL = 'Для всех'

class Languages(Enum):
    RU = 'Русский'
    EN = 'Английский'
    ANY = 'Любой'

# Модель для Tag
class Tag(models.Model):
    name = models.CharField(
        max_length=50,
        choices=[(tag.name, tag.value) for tag in Tags]
    )

    def __str__(self):
        return self.name

class Course(models.Model):
    title = models.CharField(max_length=100)

    # Выбираем уровень сложности через CharField
    difficulty_level = models.CharField(
        max_length=20,
        choices=[(tag.name, tag.value) for tag in DifficultyLevel],
        default=DifficultyLevel.FOR_BEGIN.name
    )

    price = models.DecimalField(max_digits=10, decimal_places=2)
    language = models.CharField(
        max_length=20,
        choices=[(lang.name, lang.value) for lang in Languages],
        default=Languages.RU.name
    )

    photo = models.ImageField(upload_to='photos/')
    description = models.TextField()

    # Связь многие ко многим с моделью Tag
    tags = models.ManyToManyField(Tag, related_name='courses', blank=True)




class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")  # Связь с пользователем
    name = models.CharField(max_length=100)  # Имя пользователя
    age = models.PositiveIntegerField(null=True, blank=True)  # Возраст
    city = models.CharField(max_length=100, null=True, blank=True)  # Город
    photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)  # Фото профиля

    isTeacher = models.BooleanField(default=False, verbose_name="Является преподавателем")  # Флаг преподавателя
    created_courses = models.ManyToManyField(Course, related_name="creators", blank=True)

    # Связи с курсами
    completed_courses = models.ManyToManyField(Course, related_name="completed_by", blank=True)  # Пройденные курсы
    current_courses = models.ManyToManyField(Course, related_name="currently_taken_by", blank=True)  # Текущие курсы
    favorite_courses = models.ManyToManyField(Course, related_name="favorited_by", blank=True)  # Избранные курсы

    def __str__(self):
        return f"Профиль пользователя {self.user.username}"

class Module(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True, null=True)
    video_url = models.URLField(blank=True, null=True)
    order = models.PositiveIntegerField(default=0)  # Поле для порядка отображения

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title

pythonProject/djangosite/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Course, Module, Profile
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.forms import TextInput, PasswordInput
from django.http import JsonResponse
from .forms import CourseForm, ModuleForm, PaymentForm, SearchForm, RegistrationForm, CourseFilterForm
from django.urls import reverse
from django.db.models import Q

def mainpage(request):
    courses = Course.objects.prefetch_related('tags').all()
    return render(request, 'main/index.html', {'title': 'Курсы', 'courses': courses})

def profile_pg(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'main/profile_page.html', {'profile': profile})

def coursepg(request, id):
    course = get_object_or_404(Course, id=id)
    profile = Profile.objects.get(user=request.user) if request.user.is_authenticated else None

    # Проверка, есть ли курс в избранном
    is_favorite = profile.favorite_courses.filter(id=course.id).exists() if profile else False
    has_course = (
            profile.favorite_courses.filter(id=course.id).exists() or
            profile.current_courses.filter(id=course.id).exists() or
            profile.completed_courses.filter(id=course.id).exists()
    ) if profile else False

    if request.method == 'POST' and profile:
        if 'favorite' in request.POST:
            if is_favorite:
                # Удаление из избранного
                profile.favorite_courses.remove(course)
            else:
                # Добавление в избранное
                profile.favorite_courses.add(course)
            profile.save()
            return render(request, 'main/course.html', {'course': course})  # Перезагружаем страницу с обновленными данными

    return render(request, 'main/course.html', {
        'course': course,
        'is_favorite': is_favorite,
        'has_course': has_course
    })

def search_view(request):
    form = SearchForm(request.GET or None)
    query = None
    results = []

    if form.is_valid():
        query = form.cleaned_data['query']
        results = Course.objects.filter(
            title__icontains=query
        ) | Course.objects.filter(
            description__icontains=query
        ) | Course.objects.filter(
            tags__name__icontains=query
        )
        results = results.distinct()  # Убираем дубликаты

    return render(request, 'main/search.html', {'form': form, 'query': query, 'results': results})
# Регистрация пользователя
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')  # Редирект на домашнюю страницу
    else:
        form = RegistrationForm()
    return render(request, 'main/register.html', {'form': form})

# Логин пользователя
# def user_login(request):
#     if request.method == 'POST':
#         form = AuthenticationForm(data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             login(request, user)
#             return redirect('home')  # Редирект на домашнюю страницу
#     else:
#         form = AuthenticationForm()
#     return render(request, 'main/login.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
    else:
        form = AuthenticationForm()

    # Изменение атрибутов полей формы
    form.fields['username'].widget = TextInput(attrs={
        'class': 'username',
        'placeholder': 'Имя пользователя',
    })
    form.fields['password'].widget = PasswordInput(attrs={
        'class': 'pass',
        'placeholder': 'Пароль',
    })

    if request.method == 'POST' and form.is_valid():
        user = form.get_user()
        login(request, user)
        return redirect('home')  # Редирект на домашнюю страницу

    return render(request, 'main/login.html', {'form': form})

# Выход пользователя
def user_logout(request):
    logout(request)
    return redirect('login')  # Редирект на страницу логина

def course_catalog(request):
    # Получаем все курсы из базы данных
    courses = Course.objects.all()
    return render(request, 'main/catalog.html', {'courses': courses})


def filter_courses(request):
    if not request.user.is_authenticated:
        return JsonResponse({'error': 'Пользователь не авторизован'}, status=400)

    profile = Profile.objects.get(user=request.user)

    # Получаем статус, переданный в запросе
    status = request.GET.get('status', '')

    if status == 'in_progress':
        courses = profile.current_courses.all()
    elif status == 'favorite':
        courses = profile.favorite_courses.all()
    elif status == 'completed':
        courses = profile.completed_courses.all()
    else:
        return JsonResponse({'error': 'Неизвестный статус'}, status=400)

    # Формируем данные для передачи в ответ
    course_data = []
    for course in courses:
        course_data.append({
            'id': course.id,
            'title': course.title,
            'photo': course.photo.url if course.photo else '',
        })

    return JsonResponse({'courses': course_data})

def teaching_page(request):
    if hasattr(request.user, 'profile') and request.user.profile.isTeacher:
        if request.method == 'POST':
            form = CourseForm(request.POST, request.FILES)
            if form.is_valid():
                course = form.save(commit=False)  # Создаем объект, но не сохраняем в базу
                course.save()  # Сохраняем объект
                form.save_m2m()  # Сохраняем связи ManyToMany

                # Добавляем курс в профиль пользователя
                request.user.profile.created_courses.add(course)
                request.user.profile.save()

                return redirect('catalog')  # Перенаправляем после успешного сохранения
        else:
            form = CourseForm()
        return render(request, 'main/teaching.html', {'form': form})
    else:
        return render(request, 'main/teaching.html', {'error_message': 'Войдите в аккаунт, являющийся учителем'})

def catalog(request):
    courses = Course.objects.all()

    # Получение параметров фильтров из GET-запроса
    difficulty_levels = request.GET.getlist('difficulty_level', [])
    min_price = request.GET.get('min_price')
    max_price = request.GET.get('max_price')
    free = request.GET.get('free')
    languages = request.GET.getlist('language', [])

    # Применение фильтров
    if difficulty_levels:
        courses = courses.filter(difficulty_level__in=difficulty_levels)
    if min_price:
        courses = courses.filter(price__gte=min_price)
    if max_price:
        courses = courses.filter(price__lte=max_price)
    if free:
        courses = courses.filter(price=0)
    if languages:
        courses = courses.filter(language__in=languages)

    context = {
        'courses': courses,
        'selected_difficulty_levels': difficulty_levels,
        'min_price': min_price,
        'max_price': max_price,
        'free': free,
        'selected_languages': languages,
    }

    return render(request, 'main/catalog.html', context)

from django.shortcuts import get_object_or_404, redirect
from .models import Course, Profile

def payment_view(request, course_id):
    course = get_object_or_404(Course, id=course_id)

    if request.method == 'POST':
        # После успешной оплаты связываем курс с пользователем
        if request.user.is_authenticated:
            profile = Profile.objects.get(user=request.user)
            profile.current_courses.add(course)
            profile.save()
            return render(request, 'main/course.html', {'course': course})  # Перенаправляем обратно на страницу курса

    return render(request, 'main/payment.html', {'course': course})

def edit_course(request, id):
    profile = Profile.objects.get(user=request.user)
    course = get_object_or_404(Course, id=id)
    modules = Module.objects.filter(course=course, parent__isnull=True)  # Модули верхнего уровня

    if course not in profile.created_courses.all():
        return HttpResponseForbidden("Вы не можете редактировать этот курс, так как вы не являетесь его создателем.")

    # Обработка редактирования модуля
    module_id = request.GET.get('edit_module')  # Получаем ID модуля, который нужно редактировать
    module = None
    form = None

    if module_id:
        module = get_object_or_404(Module, id=module_id, course=course)
        form = ModuleForm(request.POST or None, instance=module)
        if form.is_valid():
            form.save()
            return redirect('edit_course', id=course.id)

    # Обработка добавления нового модуля
    if request.method == 'POST' and not module_id:  # Если не редактируем, а добавляем новый модуль
        parent_id = request.POST.get('parent_id')
        title = request.POST.get('title')
        content = request.POST.get('content')
        parent = Module.objects.get(id=parent_id) if parent_id else None

        # Создаем новый модуль
        Module.objects.create(course=course, parent=parent, title=title, content=content)
        return redirect('edit_course', id=course.id)

    if request.method == 'POST' and not module_id:  # Добавление нового модуля
        parent_id = request.POST.get('parent_id')
        title = request.POST.get('title')
        content = request.POST.get('content')
        video_url = request.POST.get('video_url')  # Получаем видео URL
        parent = Module.objects.get(id=parent_id) if parent_id else None

        Module.objects.create(
            course=course,
            parent=parent,
            title=title,
            content=content,
            video_url=video_url  # Сохраняем видео URL
        )
        return redirect('edit_course', id=course.id)

    return render(request, 'main/edit_course.html', {

pythonProject/djangosite/main/templates/main/catalog.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Main page{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
{% endblock %}

{% block content %}
<div class="main-catalog">
    <div class="filter">
        <div class="filter-difficult">
            <h2>Уровень сложности</h2>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault1">
                <label class="form-check-label" for="flexCheckDefault">Для начинающих</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked2">
                <label class="form-check-label" for="flexCheckChecked">Для уверенных</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked3">
                <label class="form-check-label" for="flexCheckChecked">Для профи</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked4">
                <label class="form-check-label" for="flexCheckChecked">Для всех</label>
            </div>
        </div>

        <div class="card-container">
            <div class="card-content">
                <h2>Цена</h2>
               <div class="price-input">
        <div class="field">
          <span>Мин</span>
          <input type="number" class="input-min" value="0">
        </div>
        <div class="separator">-</div>
        <div class="field">
          <span>Макс</span>
          <input type="number" class="input-max" value="7500">
        </div>
      </div>
      <div class="slider">
        <div class="progress"></div>
      </div>
      <div class="range-input">
        <input type="range" class="range-min" min="0" max="10000" value="0" step="100">
        <input type="range" class="range-max" min="0" max="10000" value="7500" step="100">
      </div>
    </div>
            </div>

        <div class="filter-language">
            <h2>Язык</h2>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">Русский</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked6">
                <label class="form-check-label" for="flexCheckChecked">Английский</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                <label class="form-check-label" for="flexCheckChecked">Любой</label>
            </div>
        </div>
    </div>


<div class="container-catalog">
        <h1>Каталог курсов</h1>
            {% for course in courses %}
                <div class="search-course">
                <a class="a" href="{% url 'course_detail' course.id %}" >
                    <div class="course">
                        <div class="course-right">
                            {% if course.photo %}
                            <img src="{{ course.photo.url }}" alt="{{ course.title }}">
                            {% endif %}
                        </div>
                        <div class="course-left">
                            <div class="course-title">{{ course.title }}</div>
                            <div class="course-info">
                            Сложность: {{ course.get_difficulty_level_display }}<br>
                            Язык: {{ course.get_language_display }}<br>

                        </div>
                        <div class="course-description">
                             <strong>Описание:</strong>
                                {{ course.description }}
                        </div>
                            <p style="margin: 10px 0 0 0; font-weight:500; font-size: 14px; color:black;    ">{% for tag in course.tags.all %}
                                {{ tag.name }}
                                {% if not forloop.last %},
                                {% endif %}
                                {% endfor %}</p>
                        </div>
                    </div>
                </a>
                </div>
            {% empty %}
                <p>Курсы не найдены.</p>
            {% endfor %}
        </div>
    </div>

<script src="{% static 'main/js/slider.js' %}"></script>
{% endblock %}

pythonProject/djangosite/main/templates/main/course.html
{% extends 'main/layout.html' %}
{% load static %}
{% load embed_video %}

{% block title %}Main page{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'main/css/course.css' %}">
{% endblock %}

{% block content %}
    <div class="course-detail">

        <div class="header-info">

            <div class="header-title">
                <h1>{{ course.title }}</h1>
            </div>
            <div class="header-photo">
                {% if course.photo %}
                    <img src="{{ course.photo.url }}" alt="{{ course.title }} " class="scale">
                {% else %}
                    <p>Фото не доступно</p>
                {% endif %}
            </div>
        </div>
        <div class="main-course">
            <div class="left-description">
                <div class="desc">
                  <p><strong>Описание:</strong><br> {{ course.description }}</p>
                </div>
                <div class="diff-level">
                    <p><strong>Уровень сложности:</strong><br> {{ course.difficulty_level }}</p>
                </div>
                <div class="language">
                    <p><strong>Язык:</strong> {{ course.language }}</p>
                </div>


                <h3>Теги:</h3>
                <ul>
                    {% for tag in course.tags.all %}
                        <li>{{ tag.name }}</li>
                    {% empty %}
                        <li>Нет тегов</li>
                    {% endfor %}
                </ul>
                {% if request.user.is_authenticated %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="favorite-toggle">
                            <label for="favorite">
                                {% if is_favorite %}
                                    <input type="checkbox" name="favorite" id="favorite" checked> Любимое
                                {% else %}
                                    <input type="checkbox" name="favorite" id="favorite"> Любимое
                                {% endif %}
                            </label>
                        </div>
                        <div class="btn-save">
                        <button type="submit" style="margin-top: 10px;">Сохранить изменения</button>
                        </div>
                    </form>
                {% endif %}
            </div>
        <div class="btns">
                {% if has_course %}
                    <div class="have-course">
                    <p>Вы уже приобрели этот курс</p>
                    </div>
                    <a href="{% url 'course_progress' course.id %}" class="buy">
                        Перейти к прохождению
                    </a>
                {% else %}
                    <a href="{% url 'payment' course.id %}" class="buy">
                        Купить
                    </a>
                {% endif %}
                    <div class="edit-course">
                    {% if request.user.is_authenticated and course in request.user.profile.created_courses.all %}
                    <a href="{% url 'edit_course' course.id %}" class="href-edit">
                        <button>Редактировать</button>
                    </a>
                {% endif %}
                    </div>
            </div>
        </div>
</div>
{% endblock %}

pythonProject/djangosite/main/templates/main/course_progress.html
{% extends 'main/layout.html' %}
{% load static %}
{% load embed_video %}

{% block title %}Прохождение курса: {{ course.title }}{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'main/css/index.css' %}">
{% endblock %}

{% block content %}
<h1>Прохождение курса: {{ course.title }}</h1>
<div class="course-progress">

    <div class="modules-course">
        <ul>
    {% for module in modules %}
    <li>

        <a href="{% url 'module_detail' module.id %}" class="link-course-progress">{{ module.title }}</a>
        {% if module.children.all %}
        <ul>
            {% for submodule in module.children.all %}
            <li>
                <a href="{% url 'module_detail' submodule.id %}" class="link-course-progress-2">{{ submodule.title }}</a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </li>
            <div class="start-course">
        <a href="{% url 'module_detail' module.id %}">
    <button>Начать прохождение</button></a>
    {% endfor %}


    </div>
</ul>
</div>
    {% if course.photo %}
        <div class="photo-course">
                    <img src="{{ course.photo.url }}" alt="{{ course.title }} " width="400px;">
                {% else %}
                    <p>Фото не доступно</p>
                {% endif %}
    </div>
</div>
{% endblock %}

pythonProject/djangosite/main/templates/main/search.html
{% extends 'main/layout.html' %}
{% load static %}

{% block links %}
    <link rel = "stylesheet" href = "{% static 'main/css/index.css' %}">
{% endblock %}

{% block content %}
<div class="result">
<h2>Результаты для "{{ query }}":</h2>
</div>
<div class="main-catalog" style="margin-top:20px; margin-left:3%;">
    <!-- Результаты поиска -->

    <div class="filter">
        <div class="filter-difficult">
            <h2>Уровень сложности</h2>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault1">
                <label class="form-check-label" for="flexCheckDefault">Для начинающих</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked2">
                <label class="form-check-label" for="flexCheckChecked">Для уверенных</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked3">
                <label class="form-check-label" for="flexCheckChecked">Для профи</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked4">
                <label class="form-check-label" for="flexCheckChecked">Для всех</label>
            </div>
        </div>

        <div class="card-container">
            <div class="card-content">
                <h2>Цена</h2>
               <div class="price-input">
        <div class="field">
          <span>Мин</span>
          <input type="number" class="input-min" value="0">
        </div>
        <div class="separator">-</div>
        <div class="field">
          <span>Макс</span>
          <input type="number" class="input-max" value="7500">
        </div>
      </div>
      <div class="slider">
        <div class="progress"></div>
      </div>
      <div class="range-input">
        <input type="range" class="range-min" min="0" max="10000" value="0" step="100">
        <input type="range" class="range-max" min="0" max="10000" value="7500" step="100">
      </div>
    </div>
            </div>

        <div class="filter-language">
            <h2>Язык</h2>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">Русский</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked6">
                <label class="form-check-label" for="flexCheckChecked">Английский</label>
            </div>
            <div>
                <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
                <label class="form-check-label" for="flexCheckChecked">Любой</label>
            </div>
        </div>
    </div>
    {% if query %}
    <div class="column-search">
            <div style="flex-grow: 1; gap: 5px">
                {% if results %}
                {% for course in results %}
                <div class="search-course">
                <a class="a" href="{% url 'course_detail' course.id %}" >
                    <div class="course">
                        <div class="course-right">
                            {% if course.photo %}
                            <img src="{{ course.photo.url }}" alt="{{ course.title }}">
                            {% endif %}
                        </div>
                        <div class="course-left">
                            <div class="course-title">{{ course.title }}</div>
                            <div class="course-info">
                            Сложность: {{ course.get_difficulty_level_display }}<br>
                            Язык: {{ course.get_language_display }}<br>

                        </div>
                        <div class="course-description">
                             <strong>Описание:</strong>
                                {{ course.description }}
                        </div>
                            <p style="margin: 10px 0 0 0; font-weight:500; font-size: 14px; color:black;    ">{% for tag in course.tags.all %}
                                {{ tag.name }}
                                {% if not forloop.last %},
                                {% endif %}
                                {% endfor %}</p>
                        </div>
                    </div>
                </a>
                </div>
                {% endfor %}
            {% else %}
                <p>Ничего не найдено.</p>
            {% endif %} </div>
        </div>
    {% endif %}
</div>
{% endblock %}

pythonProject/djangosite/main/templates/main/teaching.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Страница преподавания{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{% static 'main/css/login.css' %}">
{% endblock %}

{% block content %}

<div style="text-align: center;">

    <h2 style="margin:30px 0 30px 0;">Создание курса</h2>

    {% if not user.profile.isTeacher %}
        <p>Войдите в аккаунт, являющийся преподавателем, чтобы создать курс.</p>
    {% else %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-reg">
                <div class="name-title">
                    {{form.title}}
                    </div>
                </div>

                <div class="description">
                    {{ form.description }}
                </div>

                <div class="diff-level_language">
                    {{ form.difficulty_level }}
                    {{ form.language }}
                </div>
                <div>
                    {{ form.price }}
                </div>

                <div>
                    {{ form.photo }}
                   <input type="file" name="photo" class="custom-photo" id="id_photo">
                    <label for="id_photo" class="custom-file-label" id="file-label">Выберите изображение</label>
                    </div>
                    <div>
                    <label for="id_tags">Теги:</label>
                    {{ form.tags }}
                </div>

                <div>
                    <label for="id_video_url">Ссылка на видео:</label>
                    {{ form.video_url }}
                </div>

                <button type="submit" class="reg">Создать курс</button>
        </form>

    {% endif %}

    <div class="login-lostpass">
        <a href="/profile" class="login">
            <div class="login">
                <p>Перейти в профиль</p>
            </div>
        </a>
    </div>
</div>

<script>
    const fileInput = document.getElementById('id_photo');
    const fileLabel = document.getElementById('file-label');

    fileInput.addEventListener('change', function() {
        if (fileInput.files.length> 0) {
        const fileName = fileInput.files[0].name;
        fileLabel.textContent = fileName;
        }
        else {
        fileLabel.textContent = 'Выберите изображение';
        }
        });
</script>

{% endblock %}